---
title: "Imported 16s sequence data which had been split into a single sample into QIIME2"
author: "xyz"
date: "2019/8/16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir="/media/sf_bigData/rootChamberWheat/qiime2pipeline")
# setwd("/media/sf_bigData/rootChamberWheat/qiime2pipeline")
```
  
[Sequence data with sequence quality information (i.e. FASTQ)](https://docs.qiime2.org/2020.2/tutorials/importing/?highlight=fastq%20manifest%20formats#singleendfastqmanifestphred33v2)  

### make metadata

```{r}
df<-data.frame(`sample-id`=paste0("A",1:54),
               `absolute-filepath`=paste0("/media/sf_bigData/rootChamberWheat/upload/A",1:54,".fastq.gz"),
               stringsAsFactors=F)
colnames(df)<-c("sample-id","absolute-filepath")
write.table(df,"metadata.tsv",quote=F,row.names = F,sep = "\t")
```

### import data

```{bash eval=F}
cd /media/sf_bigData/rootChamberWheat/qiime2pipeline
source activate qiime2-2019.4
qiime tools import \
  --type 'SampleData[SequencesWithQuality]' \
  # metadata's file name
  --input-path metadata.tsv \
  --output-path ./wheat.qza \
  --input-format SingleEndFastqManifestPhred33V2
```

